export const sexualOrientationEnum = {
  STRAIGHT: 'STRAIGHT',
  GAY: 'GAY',
  LESBIAN: 'LESBIAN',
  BISEXUAL: 'BISEXUAL',
  ASEXUAL: 'ASEXUAL',
  DEMISEXUAL: 'DEMISEXUAL',
  PANSEXUAL: 'PANSEXUAL',
  QUEER: 'QUEER',
};
