const ApiEndPoints = {
  GetOtp: 'kouple/v1/api/auth/get/otp',
  VerifyOtp: 'kouple/v1/api/auth/verify/otp',
  GetProfile: 'kouple/v1/api/account/user/profile',
  SetProfile: 'kouple/v1/api/account/user/profile',
  GetAllInterests: 'kouple/v1/api/allinterests',
  GetInterests: 'kouple/v1/api/user/interests',
  SetInterests: 'kouple/v1/api/user/interests',
  GetPhotos: 'kouple/v1/api/user/photos',
  SetPhotos: 'kouple/v1/api/user/photos',
  DeletePhotos: 'kouple/v1/api/user/photos',
  GetAllQuestions: 'kouple/v1/api/user/allquestionoptions',
  GetQuestionnaire: 'kouple/v1/api/user/questionnaire_responses',
  SetQuestionnaire: 'kouple/v1/api/user/questionnaire_responses',
  GetRecommendations: 'kouple/v1/api/recommend/profiles',
  GetProfileById: userId => `kouple/v1/api/recommend/profile/${userId}`,
  GetLikes: 'kouple/v1/api/user/likes',
  SetLikes: 'kouple/v1/api/user/likes',
  GetMatches: 'kouple/v1/api/user/matches',
  GetFeedback: 'kouple/v1/api/user/feedback',
  SetFeedback: 'kouple/v1/api/user/feedback',
  Like: 'kouple/v1/api/user/activity',
  Dislike: 'kouple/v1/api/user/activity',
  GetPlans: 'kouple/v1/api/user/premiumplans',
  GetAppSettings: 'kouple/v1/api/user/appsettings',
  SetAppSettings: 'kouple/v1/api/user/appsettings',
};

export default ApiEndPoints;
