import {SCREEN_WIDTH, SCREEN_HEIGHT} from '../../../utils/commonFunctions';

const createStyles = theme => ({
  screenContainer: {
    flex: 1,
    backgroundColor: theme.colors.grey300,
    paddingHorizontal: theme.spacing.baseUnit2,
    paddingBottom: theme.spacing.baseUnit * 5,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
  },
  seeAll: {
    ...theme.typography.regular.small600,
    color: theme.colors.grey500,
    marginTop: theme.spacing.baseUnit2,
  },
  scrollView: {
    backgroundColor: theme.colors.grey300,
  },
  addMedia: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  imageContainer: {
    width: '31.7%',
    height: 140,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.grey600,
    borderRadius: 8,
    marginRight: theme.spacing.baseUnit,
    marginTop: theme.spacing.baseUnit,
  },
  btn: {
    width: '100%',
    marginTop: theme.spacing.baseUnit2,
  },
  btn2: {
    position: 'relative',
    bottom: 0,
    width: '100%',
    marginTop: theme.spacing.baseUnit,
  },
  simpleRow: {
    flexDirection: 'row',
    paddingTop: theme.spacing.baseUnit,
  },
  pending: {
    ...theme.typography.regular.small600,
    color: theme.colors.grey500,
    marginTop: theme.spacing.baseUnit2,
    marginLeft: theme.spacing.baseUnit - 2,
  },
  verifyAdhaar: {
    width: '100%',
    borderRadius: 8,
    marginBottom: 0,
    elevation: theme.shadow.baseUnit,
    backgroundColor: theme.colors.white,
    marginTop: theme.spacing.baseUnit,
    paddingRight: theme.spacing.baseUnit,
  },
  adhaarInput: {
    ...theme.typography.regular.small600,
    flex: 1,
    borderRadius: 8,
    color: theme.colors.grey500,
    height: 40,
    backgroundColor: theme.colors.white,
  },
  verifyBtn: {
    paddingVertical: theme.spacing.baseUnit / 2,
    paddingHorizontal: theme.spacing.baseUnit2,
    backgroundColor: theme.colors.grey600,
    borderRadius: 30,
  },
  verifyText: {
    ...theme.typography.regular.smallBold,
    color: theme.colors.black600,
  },
  commonDescription: {
    ...theme.typography.regular.small600,
    color: theme.colors.grey500,
  },
  marginTop8: {
    marginTop: theme.spacing.baseUnit,
  },
  marginTop24: {
    marginTop: theme.spacing.baseUnit * 3,
  },
  selectLocation: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: theme.spacing.baseUnit + 4,
    borderRadius: 8,
    marginTop: theme.spacing.baseUnit,
    elevation: theme.shadow.baseUnit,
    paddingLeft: theme.spacing.baseUnit,
    paddingRight: theme.spacing.baseUnit2,
    backgroundColor: theme.colors.white,
  },
  input: {
    width: '100%',
    borderRadius: 8,
    color: theme.colors.grey500,
    ...theme.typography.regular.small600,
  },
  educationView: {
    borderRadius: 8,
    height: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: theme.spacing.baseUnit,
    paddingRight: theme.spacing.baseUnit2,
    marginTop: theme.spacing.baseUnit,
    elevation: theme.shadow.baseUnit,
    backgroundColor: theme.colors.white,
  },
  genderView: {
    borderRadius: 8,
    height: 40,
    padding: 2,
    width: '100%',
    marginBottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: theme.spacing.baseUnit,
    elevation: theme.shadow.baseUnit,
    backgroundColor: theme.colors.white,
  },
  genderBtn: {
    flex: 1,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    backgroundColor: theme.colors.brand500,
  },
  inactiveGenderBtn: {
    flex: 1,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
  },
  genderText: {
    ...theme.typography.regular.medium600,
    color: theme.colors.white,
  },
  inactiveGenderText: {
    ...theme.typography.regular.small600,
    color: theme.colors.black400,
  },
  bioView: {
    width: '100%',
    marginTop: theme.spacing.baseUnit,
    height: theme.spacing.baseUnit2 * 4,
    alignItems: 'flex-end',
    flexDirection: 'column',
  },
  bioInput: {
    width: '100%',
    height: theme.spacing.baseUnit2 * 3,
    ...theme.typography.regular.small600,
    color: theme.colors.black200,
    textAlignVertical: 'top',
  },
  text300: {
    ...theme.typography.regular.extraSmall,
    color: theme.colors.brandSecondary,
    marginRight: theme.spacing.baseUnit,
  },
  jobView: {
    width: '100%',
    marginBottom: 0,
  },
  marginBottom0: {
    marginTop: theme.spacing.baseUnit,
    marginBottom: 0,
  },
  jobViewFirst: {
    marginTop: theme.spacing.baseUnit,
  },
  socialFlatlist: {
    marginVertical: theme.spacing.baseUnit,
  },
  socialImageCard: {
    width: 66,
    height: 72,
    borderRadius: 8,
    marginRight: theme.spacing.baseUnit2,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.lightBrand,
  },
  image: {
    width: '100%',
    height: 140,
    borderRadius: 8,
  },
  bioError: {marginLeft: 0},
  error: {marginLeft: 0, marginTop: 0},
});

export default createStyles;
